import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
    initialScale: 1,
    width: "device-width",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-zinc-50 dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 font-sans`}
      >
      <header className="bg-white dark:bg-zinc-950 shadow-md">
          <div className="max-w-7xl mx-auto flex items-center justify-between p-4">
              <a href="/" className="flex items-center gap-2 font-bold text-blue-600">
                   BusTrackr
              </a>
              <nav className="hidden md:flex gap-6">
                  <a href="#" className="hover:text-blue-600">Accueil</a>
                  <a href="#" className="hover:text-blue-600">Favoris</a>
                  <a href="#" className="hover:text-blue-600">FAQ</a>
                  <a href="#" className="hover:text-blue-600">Contact</a>
              </nav>
              <button className="md:hidden text-xl">☰</button>
          </div>
      </header>
        <main className="max-w-5xl mx-auto p-4 space-y-8">
            {children}
        </main>
      <footer className="mt-10 bg-white dark:bg-zinc-950 text-zinc-500 dark:text-zinc-400 py-4 text-center">
          © 2025 BusTrackr – Créé par Clément L.
      </footer>
      </body>
    </html>
  );
}
